### ISSUE TITLE
Create a survey through typeform API

### ISSUE THREAD

**Issue by bbelderbos** [gtossou/survey-platform#17]
Please PR your code you had to parse an excel file and make the post request to their API. 

This is first prio right?

**Comment by bbelderbos** [comment]
Including storing the survey link in the existing `Survey` table.

**Comment by gtossou** [comment]
> Please PR your code you had to parse an excel file and make the post request to their API.
> 
> This is first prio right?

Yes. Here is the PR https://github.com/gtossou/survey-platform/pull/20

**Comment by bbelderbos** [comment]
Great job on this one!
